const CTL_DATA = [
  {
    "academicYear": "2021-2022",
    "semester": "Fall",
    "date": "Sep 28, 2021",
    "topic": "Roundtable: Best Practices for Research Assignments",
    "facilitator": "Baldino, John",
    "participants": [
      "Benscoter, Melaina",
      "Berger, Gene",
      "Berkhous, Carrie",
      "Birch, Melissa",
      "Bradigan, Nicole",
      "Burns, Alicia",
      "DeMarco, Karolyn",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Grega, Alicia",
      "Kiehart, Christine",
      "Kiron, Gopu",
      "Mosher, Jaime",
      "Ostrosky, Amy",
      "Tomlinson, Rebecca"
    ],
    "total": 16,
    "type": "Roundtable"
  },
  {
    "academicYear": "2021-2022",
    "semester": "Spring",
    "date": "Jan 18, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Berger, Gene",
      "Bradigan, Nicole",
      "Cimino, Briana",
      "Gill, Erin",
      "Gower, Shelley",
      "Kiehart, Christine",
      "Kiron, Gopu",
      "Nazarchuk, Sharon",
      "Ostrosky, Amy"
    ],
    "total": 10,
    "type": "Roundtable"
  },
  {
    "academicYear": "2021-2022",
    "semester": "Spring",
    "date": "Feb 9, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Berger, Gene",
      "Gill, Erin",
      "Kiron, Gopu",
      "Nazarchuk, Sharon"
    ],
    "total": 5,
    "type": "Roundtable"
  },
  {
    "academicYear": "2021-2022",
    "semester": "Spring",
    "date": "Mar 21, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Berger, Gene",
      "Gill, Erin",
      "Kiesendahl, Jenette"
    ],
    "total": 4,
    "type": "Roundtable"
  },
  {
    "academicYear": "2021-2022",
    "semester": "Summer I",
    "date": "Jun 8, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Berger, Gene",
      "Burns, Alicia",
      "Grega, Alicia"
    ],
    "total": 4,
    "type": "Roundtable"
  },
  {
    "academicYear": "2021-2022",
    "semester": "Summer I",
    "date": "Jun 22, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Bakanich, Dominique",
      "Berger, Gene",
      "Bradigan, Nicole",
      "Brock, Melanie",
      "Gill, Erin",
      "Gower, Shelley",
      "Hebda, Jacob",
      "Kiehart, Christine",
      "Kiron, Gopu"
    ],
    "total": 10,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Summer II",
    "date": "Jul 13, 2022",
    "topic": "Roundtable: Philosophy Across Disciplines",
    "facilitator": "Baldino, John",
    "participants": [
      "Berger, Gene",
      "Gill, Erin",
      "Kiron, Gopu"
    ],
    "total": 4,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Summer II",
    "date": "Jul 20, 2022",
    "topic": "Roundtable: Elevating Classroom Discussion",
    "facilitator": "Baldino, John",
    "participants": [
      "Berger, Gene",
      "Burns, Alicia",
      "Gill, Erin",
      "Grega, Alicia",
      "Reedy, Ashley"
    ],
    "total": 6,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Summer II",
    "date": "Jul 27, 2022",
    "topic": "Roundtable: Managing Your Digital Reputation",
    "facilitator": "Baldino, John",
    "participants": [
      "Berger, Gene",
      "Gill, Erin",
      "Grega, Alicia",
      "Hebda, Jacob",
      "Tarutis, Bill"
    ],
    "total": 6,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Fall",
    "date": "Sep 13, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "DeMarco, Karolyn",
      "Gill, Erin",
      "Gilroy-King, Susan"
    ],
    "total": 4,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Fall",
    "date": "Sep 27, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "DeMarco, Karolyn",
      "Fanelli, Brian",
      "Gill, Erin"
    ],
    "total": 5,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Fall",
    "date": "Oct 25, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Brock, Melanie",
      "Cognetti, Stacy",
      "Gill, Erin",
      "Nazarchuk, Sharon",
      "Purnell, Tyler"
    ],
    "total": 7,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Fall",
    "date": "Oct 28, 2022",
    "topic": "Headshots",
    "facilitator": "Baldino, John",
    "participants": [
      "Bakanich, Dominique",
      "Baldino, John",
      "Cognetti, Stacy",
      "Eberhart, Jeanmarie",
      "Gilroy-King, Susan",
      "Grega, Alicia",
      "Jensen, Michael",
      "Lennon, Jill",
      "McNally, Kristen",
      "Ramirez, Michelle",
      "Sebastianelli, Tracey",
      "Sorger, Tori-Lyn",
      "Von Ahnen, Chris",
      "White, Kelly"
    ],
    "total": 14,
    "type": "Headshots"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Fall",
    "date": "Nov 1, 2022",
    "topic": "Nursing: Pedagogy and Classroom Management",
    "facilitator": "Baldino, John",
    "participants": [
      "Besten, Jordyn",
      "Bolick, Noel",
      "Falkowski, Patricia",
      "Jarrow, Cassandra",
      "Lennon, Jill",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey",
      "Sulzinski, Kimberly",
      "Yontas, Janet"
    ],
    "total": 10,
    "type": "Topical Session"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Fall",
    "date": "Dec 6, 2022",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Brock, Melanie",
      "Cognetti, Stacy",
      "Elvidge, Christina",
      "Genovese, Ellen",
      "Gill, Erin",
      "Grega, Alicia",
      "Griffiths, Carrie",
      "Kiron, Gopu",
      "Locker, Desiree",
      "Zera, Angela"
    ],
    "total": 12,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Intersession",
    "date": "Jan 20, 2023",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Gill, Erin",
      "Hines, Brynn",
      "Pechal, Joanna",
      "Siarra, Matthew",
      "Zera, Angela"
    ],
    "total": 7,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "Feb 2, 2023",
    "topic": "Health Sciences: Pedagogy and Student Success",
    "facilitator": "Baldino, John",
    "participants": [
      "Bakanich, Dominique",
      "Bolick, Noel",
      "Brock, Melanie",
      "Dotzel, Mary Lou",
      "Lennon, Jill",
      "Murray, Meegan",
      "Musti, Kelly",
      "Purnell, Tyler",
      "Reedy, Ashley",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey",
      "Wormuth, Hope"
    ],
    "total": 13,
    "type": "Topical Session"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "Feb 7, 2023",
    "topic": "Roundtable: A Holistic Approach to Academic Development Students",
    "facilitator": "Baldino, John",
    "participants": [
      "Cognetti, Stacy",
      "DeMarco, Karolyn",
      "Gill, Erin",
      "Gonzalez, Marc",
      "Jensen, Michael",
      "Kiesendahl, Jenette",
      "Nazarchuk, Sharon",
      "Nolte, Cynthia",
      "Purnell, Tyler",
      "Zera, Angela"
    ],
    "total": 11,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "Feb 21, 2023",
    "topic": "Roundtable: Behavioral Intervention Team Functions and Referrals",
    "facilitator": "Baldino, John",
    "participants": [
      "Bolick, Noel",
      "Bradigan, Nicole",
      "Bruno, Taylor",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Cresswell, Tierny",
      "Gill, Erin",
      "Jensen, Michael",
      "Kiron, Gopu",
      "Liebegott, Kris",
      "Locker, Desiree",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey",
      "Zera, Angela"
    ],
    "total": 15,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "Mar 21, 2023",
    "topic": "Roundtable: Teaching and Learning Beyond our Disciplines",
    "facilitator": "Baldino, John",
    "participants": [
      "Bolick, Noel",
      "Brock, Melanie",
      "Burns, Alicia",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Elvidge, Christina",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Jensen, Michael",
      "Kiron, Gopu",
      "Locker, Desiree",
      "Purnell, Tyler",
      "Sebastianelli, Tracey"
    ],
    "total": 14,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "Apr 5, 2023",
    "topic": "Socratic Method Seminar",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Campbell, Colleen",
      "Crane, Robin",
      "DelRosso, Mary Kay",
      "DeMarco, Karolyn",
      "Eberhart, Jeanmarie",
      "Gilroy-King, Susan",
      "Grega, Alicia",
      "Imbriaco, Lisa",
      "Kiehart, Christine",
      "Kiron, Gopu",
      "Morgan, Doreen",
      "Munley, Lindsey",
      "Murray, Meegan",
      "Musti, Kelly",
      "Nazarchuk, Sharon",
      "Pechal, Joanna",
      "Purnell, Tyler"
    ],
    "total": 19,
    "type": "Topical Session"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "Apr 25, 2023",
    "topic": "Roundtable: Future Plans and Growing in Alignment with our Mission",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Bradigan, Nicole",
      "Cognetti, Stacy",
      "DeMarco, Karolyn",
      "Fanelli, Brian",
      "Gill, Erin",
      "Gower, Shelley",
      "Jensen, Michael",
      "Kiehart, Christine",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Liebegott, Kris",
      "Locker, Desiree",
      "Maskayev, Timur",
      "Murray, Meegan",
      "Musti, Kelly",
      "Nazarchuk, Sharon",
      "Pricci, Erica",
      "Pugliesi, Lawrence",
      "Zera, Angela"
    ],
    "total": 21,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "May 2, 2023",
    "topic": "Roundtable: Understanding ChatGPT and other AI",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Bauman, Jeffrey",
      "Burns, Alicia",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Cote, Julianne",
      "Craven, William",
      "DelRosso, Mary Kay",
      "DeMarco, Karolyn",
      "Genovese, Ellen",
      "Gill, Erin",
      "Jensen, Michael",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Locker, Desiree",
      "Markovich, Susan",
      "McHenry, Kathy",
      "McNally, Kristen",
      "Morgan, Doreen",
      "Nazarchuk, Sharon",
      "Purnell, Tyler",
      "Sapone, Christa",
      "Scaramuzzo, Gail",
      "Speicher, Jackie",
      "Zera, Angela"
    ],
    "total": 26,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Spring",
    "date": "May 8, 2023",
    "topic": "Nursing: Pedagogy and Classroom Management",
    "facilitator": "Baldino, John",
    "participants": [
      "Besten, Jordyn",
      "Bolick, Noel",
      "Ciesielski, April",
      "Eisenhower, Judy",
      "Falkowski, Patricia",
      "Grimes, Marcy",
      "Lennon, Jill",
      "Orden, Carol Van",
      "Pajalich, Lori",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey",
      "Sulzinski, Kimberly",
      "Yontas, Janet"
    ],
    "total": 14,
    "type": "Topical Session"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Summer I",
    "date": "Jun 6, 2023",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Gill, Erin",
      "Grega, Alicia",
      "Gumble, Sue",
      "Kiron, Gopu",
      "Purnell, Tyler",
      "Yadlosky, Jeremy"
    ],
    "total": 8,
    "type": "Roundtable"
  },
  {
    "academicYear": "2022-2023",
    "semester": "Summer I",
    "date": "Jun 23, 2023",
    "topic": "Roundtable",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Collins, Jeremy",
      "Griffiths, Carrie",
      "Kiron, Gopu",
      "Nazarchuk, Sharon",
      "Yadlosky, Jeremy"
    ],
    "total": 7,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Summer II",
    "date": "Jul 11, 2023",
    "topic": "Roundtable: Faculty Service: Opportunities and Expectations",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "McNally, Kristen",
      "Yadlosky, Jeremy"
    ],
    "total": 6,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Summer II",
    "date": "Jul 25, 2023",
    "topic": "Roundtable: Planning for Fall: What will you change based upon spring SLOs, feedback, and experiences?",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Collins, Jeremy",
      "Gill, Erin",
      "Kline, Theresa",
      "McNally, Kristen",
      "Morgan, Doreen",
      "Pugliesi, Lawrence",
      "Purnell, Tyler",
      "Scaramuzzo, Gail",
      "Wormuth, Hope"
    ],
    "total": 11,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Sep 12, 2023",
    "topic": "Roundtable: Starting the Semester: Open Discussion",
    "facilitator": "Baldino, John",
    "participants": [
      "Locker, Desiree",
      "Martin, Christine",
      "McDonough, Kevin"
    ],
    "total": 4,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Sep 22, 2023",
    "topic": "Headshots",
    "facilitator": "Baldino, John",
    "participants": [
      "Aiden, Eric",
      "Baldino, John",
      "Bauman, Jeffrey",
      "Bolick, Noel",
      "Bradigan, Nicole",
      "Craven, William",
      "DeMarco, Karolyn",
      "Eisenhower, Judy",
      "Gilroy-King, Susan",
      "Jones, Allyson",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Murray, Meegan",
      "Nicastro, Carlie",
      "Paroby, Cecilia",
      "Reedy, Ashley",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey",
      "Simon, Nick",
      "Wormuth, Hope",
      "Zera, Angela"
    ],
    "total": 21,
    "type": "Headshots"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Sep 24, 2023",
    "topic": "PTA: Grade-Norming Workshop",
    "facilitator": "Baldino, John",
    "participants": [
      "Krasniak, Cathy",
      "Murray, Meegan",
      "Musti, Kelly",
      "Reedy, Ashley"
    ],
    "total": 5,
    "type": "Topical Session"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Sep 26, 2023",
    "topic": "Roundtable: Basics of Artificial Intelligence (AI): What it Is, How it Works, and Why We Care",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Cognetti, Stacy",
      "Grega, Alicia",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Kostick, Donna",
      "Locker, Desiree",
      "Paroby, Cecilia",
      "Reedy, Ashley",
      "Wormuth, Hope",
      "Zera, Angela"
    ],
    "total": 13,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Oct 17, 2023",
    "topic": "Roundtable: College Strategic Goals and Related Project Brainstorming",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Brock, Melanie",
      "Cognetti, Stacy",
      "DelRosso, Mary Kay",
      "DeMarco, Karolyn",
      "Fanelli, Brian",
      "Jones, Allyson",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Morgan, Doreen",
      "Murray, Meegan",
      "Nazarchuk, Sharon",
      "Paroby, Cecilia",
      "Scaramuzzo, Gail"
    ],
    "total": 17,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Oct 20, 2023",
    "topic": "Social Sciences: Abuse of Power in Criminal Justice",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Collins, Jeremy",
      "Cresswell, Tierny",
      "Kline, Theresa",
      "Nazarchuk, Sharon",
      "Schneider, Kelly",
      "Zera, Angela"
    ],
    "total": 8,
    "type": "Topical Session"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Nov 6, 2023",
    "topic": "Pedagogy and Student Professionalism in Nursing",
    "facilitator": "Baldino, John",
    "participants": [
      "Besten, Jordyn",
      "Bolick, Noel",
      "Falkowski, Patricia",
      "Fields, Rebecca",
      "Lennon, Jill",
      "Pajalich, Lori",
      "Powell, Katrina",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey"
    ],
    "total": 10,
    "type": "Topical Session"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Nov 14, 2023",
    "topic": "Roundtable: Teaching and Learning with Student Athletes",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Duda, Denise",
      "Duda, Mark",
      "Jones, Allyson",
      "Larson, Erik",
      "Locker, Desiree",
      "McDonough, Kevin",
      "Morgan, Shelby",
      "Paroby, Cecilia",
      "Scaramuzzo, Gail"
    ],
    "total": 13,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Fall",
    "date": "Nov 28, 2023",
    "topic": "Roundtable: Beyond PowerPoint: Engaging Students with the Technology They Use",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Cognetti, Stacy",
      "DelRosso, Mary Kay",
      "Elvidge, Christina",
      "Genovese, Ellen",
      "Jones, Allyson",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Morgan, Doreen",
      "Reedy, Ashley",
      "Speicher, Jackie",
      "Wormuth, Hope",
      "Zera, Angela"
    ],
    "total": 15,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Intersession",
    "date": "Jan 9, 2024",
    "topic": "Roundtable: Ready, Set, Prep",
    "facilitator": "Baldino, John",
    "participants": [
      "Collins, Jeremy",
      "Jones, Allyson",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Marcotte, Tiffany",
      "O'Hara, Paige",
      "Zylberberg, Yosef"
    ],
    "total": 8,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Spring",
    "date": "Feb 6, 2024",
    "topic": "Roundtable: Starting the Semester: Open Discussion",
    "facilitator": "Baldino, John",
    "participants": [
      "Cognetti, Stacy",
      "Craven, William",
      "Cresswell, Tierny",
      "DelRosso, Mary Kay",
      "Elvidge, Christina",
      "Florovito, Brianna",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Morgan, Doreen",
      "Speicher, Jackie"
    ],
    "total": 14,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Spring",
    "date": "Feb 27, 2024",
    "topic": "Roundtable: Working with Student Athletes, Part II",
    "facilitator": "Baldino, John",
    "participants": [
      "Craven, William",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Hebda, Jacob",
      "Kiron, Gopu",
      "Locker, Desiree",
      "Morgan, Shelby",
      "Purnell, Tyler"
    ],
    "total": 9,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Spring",
    "date": "Mar 19, 2024",
    "topic": "Roundtable: The Next Level of Artificial Intelligence (AI): Integration and Detection",
    "facilitator": "Baldino, John",
    "participants": [
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Elvidge, Christina",
      "Gill, Erin",
      "Kiehart, Christine",
      "Kiron, Gopu",
      "Locker, Desiree",
      "McDonough, Kevin",
      "Speicher, Jackie"
    ],
    "total": 10,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Spring",
    "date": "Apr 3, 2024",
    "topic": "Student Life Skills",
    "facilitator": "Baldino, John",
    "participants": [
      "Cognetti, Stacy",
      "Grega, Alicia",
      "Kiron, Gopu",
      "Murray, Meegan",
      "Wormuth, Hope"
    ],
    "total": 6,
    "type": "Topical Session"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Spring",
    "date": "Apr 16, 2024",
    "topic": "Roundtable: Moderating Classroom Conversations About the Racial Divide",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Gilroy-King, Susan",
      "Jones, Allyson",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Misura, Patricia",
      "Nazarchuk, Sharon",
      "Paroby, Cecilia",
      "Wormuth, Hope",
      "Zera, Angela"
    ],
    "total": 14,
    "type": "Roundtable"
  },
  {
    "academicYear": "2023-2024",
    "semester": "Spring",
    "date": "Apr 23, 2024",
    "topic": "Roundtable: Middle States Accreditation and Institutional Strategic Plan",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Bradigan, Nicole",
      "DelRosso, Mary Kay",
      "DeMarco, Karolyn",
      "Fanelli, Brian",
      "Florovito, Brianna",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Morgan, Doreen",
      "Nazarchuk, Sharon",
      "Passenti, Jennifer",
      "Pricci, Erica",
      "Speicher, Jackie",
      "Stchur, Julianne"
    ],
    "total": 17,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Summer II",
    "date": "Jul 18, 2024",
    "topic": "Roundtable",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Colianni, Nina",
      "Jones, Allyson",
      "Kiehart, Christine",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Maskayev, Timur",
      "Morgan, Doreen",
      "Stchur, Julianne"
    ],
    "total": 10,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Summer II",
    "date": "Jul 16, 2024",
    "topic": "Roundtable: Unpopular Opinions in Higher Education: Exploring Pedagogical Ideas We're Too Shy to Share",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Maskayev, Timur",
      "Murray, Meegan"
    ],
    "total": 9,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Sep 10, 2024",
    "topic": "Roundtable: Starting the Semester: Open Discussion",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Craven, William",
      "DelRosso, Mary Kay",
      "Gilroy-King, Susan",
      "Jones, Allyson",
      "Kiehart, Christine",
      "Kiron, Gopu",
      "Locker, Desiree",
      "Maskayev, Timur",
      "Paroby, Cecilia"
    ],
    "total": 11,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Sep 3, 2024",
    "topic": "Training: New York Times in Education",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Brown, Julianne",
      "Craven, William",
      "Cresswell, Tierny",
      "DelRosso, Mary Kay",
      "DeMarco, Karolyn",
      "Fredericksen, Virginia",
      "Gilroy-King, Susan",
      "Kline, Theresa",
      "McNally, Kristen",
      "Morgan, Doreen",
      "Munley, Lindsey",
      "Seibert, Mark"
    ],
    "total": 14,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Sep 20, 2024",
    "topic": "Headshots",
    "facilitator": "Baldino, John",
    "participants": [
      "Dotzel, Mary Lou",
      "Friendy, Rachel",
      "Hebda, Jacob",
      "Lennon, Jill",
      "Paroby, Cecilia",
      "Turlip, Shauna",
      "White, Kelly"
    ],
    "total": 8,
    "type": "Headshots"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Sep 24, 2024",
    "topic": "Roundtable: Working with Adult Students in Person and Online",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Brock, Melanie",
      "Cognetti, Stacy",
      "Craven, William",
      "Cresswell, Tierny",
      "DelRosso, Mary Kay",
      "Fredericksen, Virginia",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Morgan, Doreen",
      "Paroby, Cecilia",
      "Pisak, Sara",
      "Purnell, Tyler"
    ],
    "total": 15,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Oct 3, 2024",
    "topic": "eLearning: AI in Online Instruction",
    "facilitator": "Baldino, John",
    "participants": [
      "Abdallah, Mohamed",
      "Abdullal, Manal",
      "Cognetti, Stacy",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Kostick, Donna",
      "Locker, Desiree",
      "Maskayev, Timur",
      "O'Neil, Kathleen",
      "Scaramuzzo, Gail"
    ],
    "total": 11,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Oct 15, 2024",
    "topic": "Roundtable: Fostering Engagement and Success for Traumatized Students",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Drosdick, Rachel",
      "Fredericksen, Virginia",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Kurilla, Emy",
      "Locker, Desiree",
      "Maskayev, Timur"
    ],
    "total": 9,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Oct 29, 2024",
    "topic": "Roundtable: Presenting Course Content for Multiple Learning Styles",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Maskayev, Timur",
      "Murray, Meegan"
    ],
    "total": 7,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Oct 20, 2024",
    "topic": "Unmasking AI Faculty Demo Event",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Cognetti, Stacy",
      "Craven, William",
      "Delaney, Bethann",
      "Elvidge, Christina",
      "Gilbride, Linda",
      "Gower, Shelley",
      "Karr, Dave",
      "Kiehart, Christine",
      "Kiron, Gopu",
      "Kurilla, Emy",
      "Kurpis, Charles",
      "Liebegott, Kris",
      "Maskayev, Timur",
      "McDonough, Kevin",
      "Nazarchuk, Sharon",
      "Purnell, Tyler",
      "Reppa, Penny",
      "Scaramuzzo, Gail"
    ],
    "total": 20,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Nov 18, 2024",
    "topic": "Nursing: Navigating Nursing Education",
    "facilitator": "Baldino, John",
    "participants": [
      "Besten, Jordyn",
      "Bolick, Noel",
      "Lennon, Jill",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey"
    ],
    "total": 6,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Nov 19, 2024",
    "topic": "Roundtable: Institutional Updates and Ideas: Project Peirce",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Baldino, John",
      "Bradigan, Nicole",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Cresswell, Tierny",
      "DelRosso, Mary Kay",
      "Fredericksen, Virginia",
      "Gower, Shelley",
      "Jones, Allyson",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "Morgan, Doreen",
      "Musti, Kelly",
      "Paroby, Cecilia",
      "Pricci, Erica",
      "Reedy, Ashley",
      "Scaramuzzo, Gail",
      "Urso, Danielle"
    ],
    "total": 20,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Fall",
    "date": "Nov 25, 2024",
    "topic": "CTL ENDORSED: Compassion Fatigue",
    "facilitator": "Drosdick, Rachel",
    "participants": [
      "Agentowicz, Sandra",
      "Asbury, Adrienne",
      "Bakanich, Dominique",
      "Baldino, John",
      "Besten, Jordyn",
      "Bolick, Noel",
      "Brock, Melanie",
      "Brunner, Zach",
      "DelRosso, Mary Kay",
      "Dotzel, Mary Lou",
      "Fredericksen, Virginia",
      "Gonzalez, Marc",
      "Jones, Allyson",
      "Markovich, Susan",
      "Martin, Christine",
      "Maskayev, Timur",
      "McNally, Kristen",
      "Morgan, Doreen",
      "Murray, Meegan",
      "Musti, Kelly",
      "Nazarchuk, Sharon",
      "Prudente, Maggie",
      "Reedy, Ashley",
      "Ruddy, Mary Kate",
      "Sebastianelli, Tracey",
      "Seibert, Mark",
      "Yadlosky, Jeremy"
    ],
    "total": 28,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Feb 13, 2025",
    "topic": "Roundtable: Starting the Semester: Open Discussion",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Cresswell, Tierny",
      "DeMarco, Karolyn",
      "Fredericksen, Virginia",
      "Kiesendahl, Jenette",
      "McDonough, Kevin",
      "Speicher, Jackie",
      "Yadlosky, Jeremy"
    ],
    "total": 10,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Feb 27, 2025",
    "topic": "Roundtable: Beyond Canvas: Technology-Integrated Teaching and Learning",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Brunner, Zach",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Elvidge, Christina",
      "Fredericksen, Virginia",
      "Gill, Erin",
      "Jones, Allyson",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Stchur, Julianne"
    ],
    "total": 11,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Mar 7, 2025",
    "topic": "School of Hospitality: Grade-Norming Workshop",
    "facilitator": "Baldino, John",
    "participants": [
      "Grande, Sara",
      "Marsecovich, Susan",
      "McNally, Kristen",
      "Seibert, Mark"
    ],
    "total": 5,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Mar 13, 2025",
    "topic": "PTA: The Role of Religoin in Healthcare Decision-Making",
    "facilitator": "Baldino, John",
    "participants": [
      "Krasniak, Cathy",
      "Murray, Meegan",
      "Musti, Kelly",
      "Reedy, Ashley"
    ],
    "total": 5,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Mar 17, 2025",
    "topic": "Sonography: Pedagogy, AI, and Student Professionalism",
    "facilitator": "Baldino, John",
    "participants": [
      "Allan, Daniel",
      "DelRosso, Mary Kay",
      "Hensel, Sophia",
      "Keating, Tasha",
      "Lewis, Jason",
      "Morgan, Doreen",
      "Neira, Danielle",
      "O'Connor, Marty",
      "Tirpak, Ashley"
    ],
    "total": 10,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Mar 20, 2025",
    "topic": "Roundtable: Ideas and Opportunities for Research, Publication, and other Scholarly Activities",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Fredericksen, Virginia",
      "Kiehart, Christine",
      "Kiesendahl, Jenette",
      "Mazurik, Barbara",
      "McDaniels, Stephanie",
      "Morgan, Doreen",
      "Nazarchuk, Sharon",
      "Nicastro, Carlie",
      "Paroby, Cecilia",
      "Reppa, Penny"
    ],
    "total": 11,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Apr 3, 2025",
    "topic": "Roundtable: Student Success in Career Preparation; Co-Presented with Career Services",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Cresswell, Tierny",
      "DelRosso, Mary Kay",
      "DeMarco, Karolyn",
      "Fanelli, Brian",
      "Fredericksen, Virginia",
      "Gill, Erin",
      "Jones, Allyson",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Morgan, Doreen",
      "Paroby, Cecilia",
      "Wormuth, Hope",
      "Zazzera, Charles"
    ],
    "total": 16,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Apr 10, 2025",
    "topic": "Roundtable: Institutional Updates",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Bauman, Jeffrey",
      "Bradigan, Nicole",
      "Brock, Melanie",
      "Cognetti, Stacy",
      "DelRosso, Mary Kay",
      "Fredericksen, Virginia",
      "Gonzalez, Marc",
      "Jones, Allyson",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "McDaniels, Stephanie",
      "Morgan, Doreen",
      "Murray, Meegan",
      "Nazarchuk, Sharon",
      "Pricci, Erica",
      "Prudente, Margaret",
      "Pugliesi, Lawrence",
      "Purnell, Tyler",
      "Sapone, Christa",
      "Speicher, Jackie",
      "Urso, Danielle",
      "Wormuth, Hope"
    ],
    "total": 25,
    "type": "Roundtable"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Apr 11, 2025",
    "topic": "Evaluation, Rank, and Tenure",
    "facilitator": "Baldino, John",
    "participants": [
      "Paroby, Cecilia",
      "Pugliesi, Lawrence",
      "Reppa, Penny",
      "Speicher, Jackie"
    ],
    "total": 5,
    "type": "Topical Session"
  },
  {
    "academicYear": "2024-2025",
    "semester": "Spring",
    "date": "Various",
    "topic": "One-on-One Office Hours",
    "facilitator": "Baldino, John",
    "participants": [
      "Collins, Jeremy",
      "Cresswell, Tierny",
      "Dempsey, Tim",
      "Jones, Allyson",
      "Kiesendahl, Jenette",
      "Markovich, Susan",
      "Maskayev, Timur",
      "McDonough, Kevin",
      "Nazarchuk, Sharon",
      "Reedy, Ashley",
      "Sapone, Christa",
      "Turlip, Shauna"
    ],
    "total": 13,
    "type": "Office Hours"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Summer II",
    "date": "Jul 31, 2025",
    "topic": "Roundtable: Gearing up for Fall",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Cognetti, Stacy",
      "Duda, Denise",
      "Elvidge, Christina",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Kiehart, Christine",
      "Locker, Desiree",
      "Mazurik, Barbara",
      "Nazarchuk, Sharon",
      "Reedy, Ashley"
    ],
    "total": 11,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Sep 9, 2025",
    "topic": "Roundtable: Starting the Semester: Open Discussion and Welcome Colleagues from Peirce at Lackawanna College",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Brock, Melanie",
      "Cognetti, Stacy",
      "DeMarco, Karolyn",
      "Fredericksen, Virginia",
      "Gilroy-King, Susan",
      "Hubler, Monica",
      "Hutchinson, Mike",
      "Jones, Allyson",
      "Jordan",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Kurilla, Emy",
      "Locker, Desiree",
      "Mazurik, Barbara",
      "McCrae, Sharon",
      "Rembert, DeVida",
      "Saffioti, Frank",
      "Scaramuzzo, Gail",
      "Speicher, Jackie",
      "Urso, Danielle",
      "Watson, Mark",
      "Yadlosky, Jeremy"
    ],
    "total": 24,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "",
    "topic": "Headshots",
    "facilitator": "Baldino, John",
    "participants": [
      "Armstrong, Kristin",
      "Caufman, Brittany",
      "Cresswell, Tierny",
      "Fredericksen, Virginia",
      "Harman, Travis",
      "Hebda, Jacob",
      "Kiron, Gopu",
      "Mayer, Allison",
      "Nazarchuk, Eric",
      "Pegula, Madelaine",
      "Wormuth, Hope",
      "Woytach, Karen"
    ],
    "total": 14,
    "type": "Headshots"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Sep 4, 2025",
    "topic": "Kickoff Party",
    "facilitator": "Baldino, John",
    "participants": [
      "Bauman, Jeffrey",
      "Brock, Melanie",
      "Crane, Robin",
      "Craven, William",
      "Decker, Stephanie",
      "DeMarco, Karolyn",
      "Elvidge, Christina",
      "Fanelli, Brian",
      "Fredericksen, Virginia",
      "Gonzalez, Marc",
      "Harman, Travis",
      "Johns, Patricia",
      "Karr, Dave",
      "Kiron, Gopu",
      "Kurpis, Charles",
      "Larson, Denise",
      "Locker, Desiree",
      "Lombardi, Lawrence",
      "Mazurik, Barbara",
      "McDonough, Kevin",
      "Montague, Dana",
      "Musti, Kelly",
      "Nazarchuk, Sharon",
      "Nowogorski, Barbara",
      "Pegula, Madelaine",
      "Pieczynski, Thomas",
      "Reedy, Ashley",
      "Roberts, John",
      "Urso, Danielle",
      "Yadlosky, Jeremy"
    ],
    "total": 32,
    "type": "Kickoff"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Sep 23, 2025",
    "topic": "Roundtable: Working with Adult Learners in Person and Online",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Brown, Julianne",
      "Caufman, Brittany",
      "Cognetti, Stacy",
      "Cresswell, Tierny",
      "Fanelli, Brian",
      "Fredericksen, Virginia",
      "Gilroy-King, Susan",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Locker, Desiree",
      "McCrae, Sharon",
      "McDonough, Kevin",
      "Nazarchuk, Sharon",
      "Plunkett, Frank",
      "Renz, Nolan",
      "Saffioti, Frank",
      "Witmer, Shawn"
    ],
    "total": 20,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Sep 23, 2025",
    "topic": "Academic Develoment: The New York Times in Education",
    "facilitator": "Baldino, John",
    "participants": [
      "DeMarco, Karolyn",
      "Gower, Shelley",
      "Kiehart, Christine",
      "Kiesendahl, Jenette"
    ],
    "total": 6,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Oct 1, 2025",
    "topic": "Sunbury Center: The New York Times in Education",
    "facilitator": "Baldino, John",
    "participants": [
      "Bolig, Kimberly",
      "Ciucci, Angela",
      "Hieneman, Albra",
      "Hill, Laura",
      "Mahoney, Ted",
      "McDermott, Paul",
      "Newbern, Jewel",
      "O'Brien, Thomas",
      "Sempko, Cristyn"
    ],
    "total": 11,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Oct 14, 2025",
    "topic": "Roundtable: Working with College-Age and High School Learners in Person and Online",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Caufman, Brittany",
      "Cognetti, Stacy",
      "Fredericksen, Virginia",
      "Kiron, Gopu",
      "Locker, Desiree",
      "McCrae, Sharon"
    ],
    "total": 8,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Oct 21, 2026",
    "topic": "PTA: The New York Times in Education",
    "facilitator": "Baldino, John",
    "participants": [
      "Murray, Meegan",
      "Reedy, Ashley"
    ],
    "total": 4,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Oct 23, 2026",
    "topic": "Philadelphia Center: The New York Times in Education",
    "facilitator": "Baldino, John",
    "participants": [
      "Blocker, Benjamin",
      "Campbell, Christopher",
      "Cook, Lindsay",
      "Coyle, Patrick",
      "Currie, Linda",
      "Curry, Claudia",
      "Dawkins, Michael",
      "Donovan, Stephanie",
      "Eid, Zaman",
      "Glenn, Charlene",
      "Guzzo, Lauren",
      "Hubler, Monica",
      "Janoff, Howard",
      "Jones, Julie",
      "Jordan, Kevin",
      "Kempf, Ivy",
      "Loggains, Jamie",
      "Makalintal, Maria",
      "Marola, Gene",
      "Mitchell-Green, Sheila",
      "Place, Carl",
      "Plunkett, Frank",
      "Purnell, Sylvia",
      "Rice, Diane",
      "Schultz, John",
      "Singleton, Milika",
      "Toliver, Rita",
      "Torres, Barbara",
      "Tran, Tam",
      "Washington, Alichia",
      "Watson, Kate",
      "Zarko, Gina"
    ],
    "total": 34,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Oct 28, 2025",
    "topic": "Roundtable: Managing an Age-Diverse Classroom in Person and Online",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Cognetti, Stacy",
      "Cresswell, Tierny",
      "Fredericksen, Virginia",
      "Gilroy-King, Susan",
      "Gonzalez, Marc",
      "Kiron, Gopu",
      "Locker, Desiree",
      "Maskayev, Timur",
      "Mazurik, Barbara",
      "McCrae, Sharon",
      "Saffioti, Frank",
      "Scaramuzzo, Gail",
      "Yadlosky, Jeremy"
    ],
    "total": 16,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Nov 18, 2025",
    "topic": "Roundtable: Institutional Updates with Guests Dr. Erica Pricci and Adrienne Asbury",
    "facilitator": "Zazzera, Charles",
    "participants": [
      "Collins, Jeremy",
      "Fanelli, Brian",
      "Jones, Allyson",
      "Kurilla, Emy",
      "Nazarchuk, Sharon"
    ],
    "total": 6,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Dec 4, 2025",
    "topic": "Roundtable: Institutional Updates",
    "facilitator": "Baldino, John",
    "participants": [
      "Asbury, Adrienne",
      "Brock, Melanie",
      "Brown, Julianne",
      "Currie, Linda",
      "Donovan, Stephanie",
      "Evanoski, Richard Stephen",
      "Fanelli, Brian",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Gower, Shelley",
      "Inciardi, Kristin",
      "Kiron, Gopu",
      "Morgan, Doreen",
      "Nazarchuk, Sharon",
      "Pricci, Erica",
      "Ramirez, Sergio",
      "Schneider, Kelly",
      "Terraciano, Michael",
      "Urso, Danielle",
      "Yadlosky, Jeremy"
    ],
    "total": 21,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Fall",
    "date": "Various",
    "topic": "One-on-One Office Hours",
    "facilitator": "Baldino, John",
    "participants": [
      "Bujno, Steve",
      "Cresswell, Tierny",
      "Jones, Allyson",
      "McDonough, Kevin",
      "Reedy, Ashley",
      "Turlip, Shauna"
    ],
    "total": 8,
    "type": "Office Hours"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Jan 20, 2026",
    "topic": "PTA: Strategies for Student Success",
    "facilitator": "Baldino, John",
    "participants": [
      "Murray, Meegan",
      "Reedy, Ashley"
    ],
    "total": 3,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Feb 5, 2026",
    "topic": "Roundtable: Starting the Semester: Open Discussion",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Bradigan, Nicole",
      "Brogden, Joanne",
      "Cognetti, Stacy",
      "Cresswell, Tierny",
      "Currie, Linda",
      "DeMarco, Karolyn",
      "Fanelli, Brian",
      "Fredericksen, Virginia",
      "Grasty, LaKeyya",
      "Inciardi, Kristin",
      "Kiron, Gopu",
      "McCrae, Sharon",
      "Morgan, Doreen",
      "Nazarchuk, Sharon",
      "Pannell, Marguerite",
      "Plunkett, Frank",
      "Reppa, Penny",
      "Yadlosky, Jeremy"
    ],
    "total": 19,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Feb 19, 2026",
    "topic": "Social Sciences: Student Professionalism",
    "facilitator": "Baldino, John",
    "participants": [
      "Bradigan, Nicole",
      "Collins, Jeremy",
      "Cresswell, Tierny",
      "Kline, Theresa",
      "Nazarchuk, Sharon",
      "Schneider, Kelly"
    ],
    "total": 7,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Feb 26, 2026",
    "topic": "Roundtable: We're the Face: Positioning the Merger to our Students",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Brogden, Joanne",
      "Coyle, Patrick",
      "Currie, Linda",
      "DeMarco, Karolyn",
      "Donovan, Stephanie",
      "Fredericksen, Virginia",
      "Gilroy-King, Susan",
      "Glenn, Charlene",
      "Jones, Allyson",
      "Kiesendahl, Jenette",
      "Kiron, Gopu",
      "Loggains, Jamie",
      "Makalintal, Maria",
      "Mazurik, Barbara",
      "McCrae, Sharon",
      "McDonough, Kevin",
      "Nazarchuk, Sharon",
      "Pannell, Marguerite",
      "Plunkett, Frank"
    ],
    "total": 20,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Mar 12, 2026",
    "topic": "Roundtable: Identifying New Opportunities for Faculty as LC and PC Become One",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Brogden, Joanne",
      "Currie, Linda",
      "Donovan, Stephanie",
      "Nazarchuk, Sharon",
      "Pannell, Marguerite",
      "Plunkett, Frank",
      "Speicher, Jackie",
      "Thomas, Tracey"
    ],
    "total": 9,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Apr 23, 2026",
    "topic": "Philadelphia Center: Student Professionalism",
    "facilitator": "Baldino, John",
    "participants": [
      "Campbell, Christopher",
      "Coyle, Patrick",
      "Currie, Linda",
      "Donovan, Stephanie",
      "Glenn, Charlene",
      "Inciardi, Kristin",
      "Kempf, Ivy",
      "Loggains, Jamie",
      "Pannell, Marguerite",
      "Plunkett, Frank",
      "Schultz, John",
      "Singleton, Milika",
      "Toliver, Rita",
      "Torres, Barbara"
    ],
    "total": 15,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Apr 5, 2026",
    "topic": "OTA: Student Professionalism",
    "facilitator": "Baldino, John",
    "participants": [
      "Brock, Melanie",
      "Wormuth, Hope"
    ],
    "total": 3,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Apr 9, 2026",
    "topic": "Roundtable: Institutional Updates with Guests: Dr. Erica Pricci, Dr. Kelly Musti, and Adrienne Asbury",
    "facilitator": "Collins, Jeremy",
    "participants": [
      "Asbury, Adrienne",
      "Bakanich, Dominique",
      "Bradigan, Nicole",
      "Brock, Melanie",
      "Brogden, Joanne",
      "Brown, Julianne",
      "Cognetti, Stacy",
      "Collins, Jeremy",
      "Coyle, Patrick",
      "Currie, Linda",
      "Donovan, Stephanie",
      "Gill, Erin",
      "Gilroy-King, Susan",
      "Inciardi, Kristin",
      "Kempf, Ivy",
      "Kiron, Gopu",
      "Kline, Theresa",
      "Lawrence (Unverified)",
      "Loggains, Jamie",
      "Morgan, Doreen",
      "Murray, Meegan",
      "Musti, Kelly",
      "Pannell, Marguerite",
      "Plunkett, Frank",
      "Pricci, Erica",
      "Prudente, Margaret",
      "Reedy, Ashley",
      "Reppa, Penny",
      "Saffioti, Frank",
      "Schultz, John",
      "Singleton, Milika",
      "Speicher, Jackie",
      "Toliver, Rita",
      "Torres, Barbara",
      "Urso, Danielle"
    ],
    "total": 35,
    "type": "Roundtable"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Apr 10, 2026",
    "topic": "Evaluation, Rank, and Tenure",
    "facilitator": "Baldino, John",
    "participants": [
      "Brown, Julianne",
      "Kline, Theresa",
      "McDonough, Kevin"
    ],
    "total": 5,
    "type": "Topical Session"
  },
  {
    "academicYear": "2025-2026",
    "semester": "Spring",
    "date": "Various",
    "topic": "One-on-One Office Hours",
    "facilitator": "Baldino, John",
    "participants": [
      "Misura, Patricia",
      "Turlip, Shauna"
    ],
    "total": 3,
    "type": "Office Hours"
  }
];
